### ISSUE TITLE
Falsche Übersetzungen (Caching?)

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#21]
Siehe Sreenshots ist der Email Betreff auf den Tenant deinKlima angepasst, Emails werden jedoch mit dem falschen Subject "Open Community Luzern ..." versendet. Den Cache habe ich mehrfach geleert, Problem bleibt bestehen. Haben wir ein Caching-Problem oder ist diese falsche Übersetzung allenfalls irgendwo noch auf Code-Ebene definiert, weshalb die Übersetzung mit Term Customizer nicht greift?

Getetest auf PROD, da INT nur auf Einladung und somit keine Registrierung zugelassen.

<img width="1232" alt="Bildschirmfoto 2022-09-14 um 08 49 37" src="https://user-images.githubusercontent.com/75796635/190085175-314297e2-1b33-486e-92a1-ccb583e2f7f2.png">

<img width="1155" alt="Bildschirmfoto 2022-09-14 um 08 42 24" src="https://user-images.githubusercontent.com/75796635/190085232-62de1b7d-19ac-43bd-bad4-45a2f9aa525e.png">

**Comment by bsantschi** [comment]
Möglicherweise dasselbe Problem, das @Kagemaru hier bereits am Anschauen ist: https://github.com/stadtluzern/decidim-ocl/issues/225

**Comment by innosmith** [comment]
> Möglicherweise dasselbe Problem, das @Kagemaru hier bereits am Anschauen ist: [stadtluzern/decidim-ocl#225](https://github.com/stadtluzern/decidim-ocl/issues/225)

Sehr wahrscheinlich dasselbe Problem @bsantschi , @Kagemaru , @Naadjjaa . Für deinKlima könnte das zum Launch-"Bremser" werden.

**Comment by larsUE** [comment]
Ist auf gemeinsamer.space auch so, trotz Term Customizer Anpassung.
Ich sehe, dass die Luzern im Sprachfile so erwähnt wird. Mein Vorschlag wäre nun, "Open Community Luzern" (das ist ja nicht mal für Luzern richtig) durch %{organization} zu ersetzen. Das könnte ich machen, danach bräuchten wir einen INT-Release um zu testen.

Was denkt ihr, @Kagemaru @Naadjjaa und @innosmith ?

**Comment by innosmith** [comment]
Wenn das funktioniert @larsUE , sehr gerne umsetzen.

**Comment by Kagemaru** [comment]
@bsantschi: Ja, es ist das gleiche Problem

@larsUE: Ich glaube nicht, dass die Organisation dort reingegeben wird, somit ist sie dann auch nicht im String verwendbar

@bsantschi, @Naadjjaa, @innosmith, @larsUE:
Ich denke, ich habe nun den Ursprung gefunden, wo es schiefläuft (leider nicht warum). Ein Fix dafür ist es, die Mail Templates zu überschreiben, die hier verwendet werden.
Beim nächsten INT Release, wird dies testbar sein. Ich update hier, wenn es deployt ist.

**Comment by Kagemaru** [comment]
Ich habe unser Problem bei TermCustomizer als Issue erstellt:
https://github.com/mainio/decidim-module-term_customizer/issues/93

**Comment by bsantschi** [comment]
Bis der [Fehler bei TermCustomizer](https://github.com/mainio/decidim-module-term_customizer/issues/93) geflickt wird, könnten wir das Problem umgehen, indem wir generische/gemeinsame E-Mailtitel für alle Tenants definieren. Die E-Mail-Inhalte sollten wir pro Tenant unterschiedlich machen können, jedoch nicht im TermCustomizer, sondern direkt im Code. Folgende Übersetzungen sind davon betroffen:

Edit Thomas: Translation keys, siehe unten

**Comment by Kagemaru** [comment]
Dies sollte jetzt endlich behoben sein: https://github.com/stadtluzern/decidim-ocl/projects/1#card-85328903

Folgende Keys wurden für dialogluzern spezifisch übersetzt:
```yaml
--- 
devise: 
  mailer: 
    confirmation_instructions: 
      action: "Bestätige dein Konto"
      greeting: "Willkommen %{recipient}!"
      instruction: "Du kannst deine E-Mail-Adresse über den folgenden Link bestätigen:"
    email_changed: 
      greeting: "Hallo %{recipient}!"
      message: "Wir schreiben dir, um dich darüber zu informieren, dass deine E-Mail-Adresse zu %{email} geändert wurde."
      message_unconfirmed: "Wir schreiben dir, um dich darüber zu informieren, dass deine E-Mail-Adresse zu %{email} geändert wurde."
    invitation_instructions: 
      accept: "Die Einladung annehmen"
      accept_until: "Diese Einladung wird in %{due_date} fällig."
      decline: "Einladung ablehnen"
      hello: "Hallo %{email},"
      ignore: "Wenn du die Einladung nicht annehmen möchtest, ignoriere diese E-Mail.<br /> Dein Konto wird erst erstellt, Wenn du auf den obigen Link zugreifst und deinen Benutzernamen und dein Passwort festlegst."
      invited_you_as_admin: "%{invited_by} hat dich als Admin von %{application} eingeladen. Du kannst es über den folgenden Link akzeptieren."
      invited_you_as_private_user: "%{invited_by} hat dich als private/n Benutzer/in von %{application} eingeladen. Du kannst es über den folgenden Link akzeptieren."
      someone_invited_you: "Jemand hat dich zu %{application} eingeladen. Du kannst die Einladung über den folgenden Link akzeptieren."
      someone_invited_you_as_admin: "Jemand hat dich als Admin von %{application} eingeladen, du kannst die Einladung über den untenstehenden Link akzeptieren."
      someone_invited_you_as_private_user: "Jemand hat dich als private_user von %{application} eingeladen, du kannst die Einladung über den folgenden Link akzeptieren."
    password_change: 
      greeting: "Hallo %{recipient}!"
      message: "Wir kontaktieren dich, um dich darüber zu informieren, dass dein Passwort geändert wurde."
      subject: "Passwort geändert"
    reset_password_instructions: 
      action: "Mein Passwort ändern"
      greeting: "Hallo %{recipient}!"
      instruction: "Jemand hat einen Link angefordert, um dein Passwort zu ändern. Falls du das selbst warst, dann folge diesem Link:"
      instruction_2: "Falls du das nicht selbst warst, kannst du diese E-Mail ignorieren."
      instruction_3: "Dein Passwort ändert sich erst, wenn du auf den obigen Link zugreifst und ein neues Passwort erstellst."
    unlock_instructions: 
      action: "Entsperre mein Konto"
      greeting: "Hallo %{recipient}!"
      instruction: "Klicke auf den folgenden Link, um dein Konto zu entsperren:"
      message: "Dein Konto wurde aufgrund einer übermässigen Anzahl fehlgeschlagener Anmeldeversuche gesperrt."
```

Falls ihr auch eigene spezifische Übersetzungen wollt, brauche ich alle diese Einträge übersetzt (ganz oder gar nicht).
Ansonsten werden die Standardübersetzungen verwendet. Wenn sich alle einig sind, kann man auch daran noch schrauben.
