### ISSUE TITLE
Anordnung Team-Profilbilder

### ISSUE THREAD

**Issue by innosmith** [decidim-swiss/decidim.swiss#9]
Siehe Screenshot werden Profilbilder standardmässig vertikal angezeigt. Wäre es möglich, dies zuerst horizontal - und wenn zu viele - auf einer weiteren Zeile anzuzeigen?

<img width="1328" alt="Bildschirmfoto 2022-08-10 um 10 24 59" src="https://user-images.githubusercontent.com/75796635/183856497-dc4b67ee-6ab2-476c-be71-df9af40c9031.png">

**Comment by carlobeltrame** [comment]
Ja, dafür müssen wir nur folgendes CSS von Dialog Luzern übernehmen:
```css
.assembly-members-list .author__avatar {
	 display: initial;
	 margin: 0 -0.6rem 0.5rem;
}
```
